apiVersion: apps/v1
kind: Deployment
metadata:
  name: gorzenetes
spec:
  replicas: 3
  selector:
    matchLabels:
      type: api
      service: gorzenetes-service
  template:
    metadata:
      labels:
        type: api
        service: gorzenetes-service
    spec:
      containers:
      - image: otanikotani/gorzenetes:latest
        name: gorzenetes
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /foo
            port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: gorzenetes
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    type: api
    service: gorzenetes-service