name: Release

on:
  push:
    branches:
      - master

jobs:

  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: debug if needed
        run: |
          export DEBUG=${DEBUG:-false}
          if [[ "$DEBUG" == "true" ]]; then
            env
          fi
        env:
          DEBUG: ${{secrets.DEBUG}}

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: build and test
        run: |
          echo $TZ
          go test -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...
        env:
          TZ: US/Eastern

      - name: install golangci-lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.23.1

      - name: run linters
        run: ./golangci-lint run --config ./.golangci.yml ./... ;

      - name: upload coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: $GITHUB_WORKSPACE/profile.cov

  release:
    name: Semantic release
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/github
            @semantic-release/release-notes-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validates GO releaser config
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: check

      - name: Create release on GitHub
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build image
        run:  docker build --build-arg SKIP_TEST=true --build-arg CI=github .

      - name: Publish
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: otanikotani/gorzenetes
          tag: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}