name: Release

on:
  push:
    branches:
      - master

jobs:

  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: debug if needed
        run: |
          export DEBUG=${DEBUG:-false}
          if [[ "$DEBUG" == "true" ]]; then
            env
          fi
        env:
          DEBUG: ${{secrets.DEBUG}}

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: build and test
        run: |
          echo $TZ
          go test -timeout=60s -covermode=count -coverprofile=profile.cov ./...
        env:
          TZ: US/Eastern

      - name: install golangci-lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.23.1

      - name: run linters
        run: ./golangci-lint run --config ./.golangci.yml ./... ;

      - name: upload coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov

  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build image
        run:  docker build --build-arg SKIP_TEST=true --build-arg CI=github .

      - name: Publish
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: otanikotani/gorzenetes
          registry: docker.io
          tag: 1.0
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}